#!/bin/bash
symbols=(EOSUSDT XRPUSDT BCHUSDT XTZUSDT LINKUSDT ADAUSDT DOTUSDT UNIUSDT XEMUSDT SUSHIUSDT AAVEUSDT DOGEUSDT MATICUSDT ETCUSDT BNBUSDT FILUSDT XLMUSDT TRXUSDT VETUSDT THETAUSDT COMPUSDT AXSUSDT SANDUSDT MANAUSDT KSMUSDT ATOMUSDT CHZUSDT CRVUSDT ENJUSDT GRTUSDT SHIB1000USDT YFIUSDT BSVUSDT ICPUSDT FTMUSDT ALGOUSDT DYDXUSDT NEARUSDT SRMUSDT OMGUSDT IOSTUSDT DASHUSDT FTTUSDT BITUSDT GALAUSDT CELRUSDT HBARUSDT ONEUSDT C98USDT MKRUSDT COTIUSDT ALICEUSDT EGLDUSDT RENUSDT TLMUSDT RUNEUSDT ILVUSDT FLOWUSDT WOOUSDT LRCUSDT ENSUSDT IOTXUSDT CHRUSDT BATUSDT STORJUSDT SNXUSDT SLPUSDT ANKRUSDT LPTUSDT QTUMUSDT CROUSDT SXPUSDT YGGUSDT ZECUSDT IMXUSDT SFPUSDT AUDIOUSDT ZENUSDT SKLUSDT GTCUSDT LITUSDT CVCUSDT RNDRUSDT SCUSDT RSRUSDT STXUSDT MASKUSDT CTKUSDT BICOUSDT REQUSDT 1INCHUSDT KLAYUSDT SPELLUSDT ANTUSDT DUSKUSDT ARUSDT REEFUSDT XMRUSDT PEOPLEUSDT IOTAUSDT CELOUSDT WAVESUSDT RVNUSDT KNCUSDT KAVAUSDT ROSEUSDT DENTUSDT CREAMUSDT LOOKSUSDT JASMYUSDT 10000NFTUSDT HNTUSDT ZILUSDT NEOUSDT RAYUSDT CKBUSDT SUNUSDT JSTUSDT BANDUSDT RSS3USDT OCEANUSDT 1000BTTUSDT API3USDT PAXGUSDT ANCUSDT KDAUSDT APEUSDT GMTUSDT OGNUSDT BSWUSDT CTSIUSDT CTSIUSDT CTSIUSDT CTSIUSDT CTSIUSDT CTSIUSDT CTSIUSDT )
for i in "${symbols[@]}"
do
    :
    echo "Kill screen for $i"
    screen -S "bybit_pro_$i" -X quit
done

