from copy import deepcopy

from .optimize_bounds import get_optimize_bounds_defaults
from .strategy import DEFAULT_STRATEGY_KIND, get_all_strategy_defaults


CONFIG_SCHEMA_VERSION = "v8.0.0"
DEFAULT_EXAMPLE_CONFIG_PATH = "configs/examples/default_trailing_martingale_long_npos4.json"


def _get_shared_bot_defaults():
    return {
        "long": {
            "risk": {
                "entry_cooldown_minutes": 0.4,
                "n_positions": 4,
                "total_wallet_exposure_limit": 1.5,
                "total_exposure_enforcer_enabled": True,
                "total_exposure_enforcer_threshold": 0.985,
                "we_excess_allowance_pct": 0.1,
                "position_exposure_enforcer_enabled": True,
                "position_exposure_enforcer_threshold": 0.99,
            },
            "forager": {
                "score_weights": {
                    "ema_readiness": 0.058823529411764705,
                    "volatility": 0.7156862745098039,
                    "volume": 0.22549019607843138,
                },
                "volatility_ema_span_1m": 110,
                "volume_drop_pct": 0.02,
                "volume_ema_span_1m": 760,
            },
            "hsl": {
                "cooldown_minutes_after_red": 2721,
                "ema_span_minutes": 1371,
                "enabled": False,
                "no_restart_drawdown_threshold": 1,
                "orange_tier_mode": "tp_only_with_active_entry_cancellation",
                "panic_close_order_type": "limit",
                "red_threshold": 0.013,
                "tier_ratios": {"orange": 0.75, "yellow": 0.5},
            },
            "unstuck": {
                "close_pct": 0.089,
                "ema_dist": -0.033,
                "enabled": True,
                "loss_allowance_pct": 0.0252,
                "threshold": 0.408,
            },
        },
        "short": {
            "risk": {
                "entry_cooldown_minutes": 0.0,
                "n_positions": 1,
                "total_wallet_exposure_limit": 0,
                "total_exposure_enforcer_enabled": True,
                "total_exposure_enforcer_threshold": 0.8,
                "we_excess_allowance_pct": 0,
                "position_exposure_enforcer_enabled": True,
                "position_exposure_enforcer_threshold": 0.8,
            },
            "forager": {
                "score_weights": {
                    "ema_readiness": 1.0,
                    "volatility": 0.0,
                    "volume": 0.0,
                },
                "volatility_ema_span_1m": 10,
                "volume_drop_pct": 0.02,
                "volume_ema_span_1m": 360,
            },
            "hsl": {
                "cooldown_minutes_after_red": 1,
                "ema_span_minutes": 1,
                "enabled": False,
                "no_restart_drawdown_threshold": 1,
                "orange_tier_mode": "tp_only_with_active_entry_cancellation",
                "panic_close_order_type": "limit",
                "red_threshold": 0.01,
                "tier_ratios": {"orange": 0.75, "yellow": 0.5},
            },
            "unstuck": {
                "close_pct": 0.05,
                "ema_dist": -0.2,
                "enabled": True,
                "loss_allowance_pct": 0.005,
                "threshold": 0.4,
            },
        },
    }


def get_template_config():
    return deepcopy(
        {
            "config_version": CONFIG_SCHEMA_VERSION,
            "backtest": {
                "aggregate": {
                    "default": "mean",
                },
                "balance_sample_divider": 60,
                "base_dir": "backtests",
                "btc_collateral_cap": 0.0,
                "btc_collateral_ltv_cap": None,
                "candle_interval_minutes": 2,
                "coin_sources": {},
                "compress_cache": True,
                "dynamic_wel_by_tradability": True,
                "end_date": "now",
                "exchanges": ["binance", "bybit"],
                "filter_by_min_effective_cost": False,
                "gap_tolerance_ohlcvs_minutes": 120,
                "hlcvs_data_dir": None,
                "hlcvs_data_override_mode": "intersection",
                "liquidation_threshold": 0.05,
                "maker_fee_override": 0.0004,
                "market_settings_sources": {},
                "ohlcv_source_dir": None,
                "market_order_slippage_pct": 0.0005,
                "visible_metrics": None,
                "scenarios": [
                    {"label": "base"},
                    {
                        "exchanges": ["binance"],
                        "label": "binance_only",
                    },
                    {
                        "exchanges": ["bybit"],
                        "label": "bybit_only",
                    },
                    {
                        "coins": [
                            "BTC",
                            "ETH",
                            "BNB",
                            "XRP",
                            "SOL",
                            "TRX",
                            "DOGE",
                            "HYPE",
                            "ADA",
                            "ZEC",
                        ],
                        "label": "subset_1_top",
                    },
                    {
                        "coins": [
                            "BCH",
                            "LINK",
                            "XMR",
                            "CC",
                            "TON",
                            "XLM",
                            "SUI",
                            "LTC",
                            "M",
                        ],
                        "label": "subset_2_mid1",
                    },
                    {
                        "coins": [
                            "AVAX",
                            "HBAR",
                            "SHIB",
                            "CRO",
                            "TAO",
                            "UNI",
                            "DOT",
                            "MNT",
                            "WLFI",
                        ],
                        "label": "subset_3_mid2",
                    },
                    {
                        "coins": [
                            "NEAR",
                            "ONDO",
                            "OKB",
                            "ASTER",
                            "PEPE",
                            "SKY",
                            "ICP",
                            "AAVE",
                            "ETC",
                            "MORPHO",
                        ],
                        "label": "subset_4_bottom",
                    },
                    {
                        "coins": [
                            "BTC",
                            "SOL",
                            "ADA",
                            "XMR",
                            "SUI",
                            "HBAR",
                            "UNI",
                            "NEAR",
                            "PEPE",
                            "ETC",
                        ],
                        "label": "subset_5_mix",
                    },
                    {
                        "coins": [
                            "ETH",
                            "TRX",
                            "ZEC",
                            "CC",
                            "LTC",
                            "SHIB",
                            "DOT",
                            "ONDO",
                            "SKY",
                            "MORPHO",
                        ],
                        "label": "subset_6_mix",
                    },
                    {
                        "coins": [
                            "BNB",
                            "DOGE",
                            "BCH",
                            "TON",
                            "M",
                            "CRO",
                            "MNT",
                            "OKB",
                            "ICP",
                        ],
                        "label": "subset_7_mix",
                    },
                    {
                        "coins": [
                            "XRP",
                            "HYPE",
                            "LINK",
                            "XLM",
                            "AVAX",
                            "TAO",
                            "WLFI",
                            "ASTER",
                            "AAVE",
                        ],
                        "label": "subset_8_mix",
                    },
                    {
                        "label": "n_positions_3",
                        "overrides": {"bot.long.risk.n_positions": 3, "bot.short.risk.n_positions": 3},
                    },
                    {
                        "label": "n_positions_4",
                        "overrides": {"bot.long.risk.n_positions": 4, "bot.short.risk.n_positions": 4},
                    },
                    {
                        "label": "n_positions_5",
                        "overrides": {"bot.long.risk.n_positions": 5, "bot.short.risk.n_positions": 5},
                    },
                    {
                        "label": "n_positions_6",
                        "overrides": {"bot.long.risk.n_positions": 6, "bot.short.risk.n_positions": 6},
                    },
                ],
                "start_date": "2021-01-01",
                "starting_balance": 100000,
                "suite_enabled": False,
                "taker_fee_override": None,
                "volume_normalization": True,
            },
            "bot": {
                "long": {
                    **deepcopy(_get_shared_bot_defaults()["long"]),
                    "strategy": get_all_strategy_defaults()["long"],
                },
                "short": {
                    **deepcopy(_get_shared_bot_defaults()["short"]),
                    "strategy": get_all_strategy_defaults()["short"],
                },
            },
            "coin_overrides": {},
            "live": {
                "approved_coins": {
                    "long": [
                        "AAVE",
                        "ADA",
                        "ASTER",
                        "AVAX",
                        "BCH",
                        "BNB",
                        "BTC",
                        "CC",
                        "CRO",
                        "DOGE",
                        "DOT",
                        "ETC",
                        "ETH",
                        "HBAR",
                        "HYPE",
                        "ICP",
                        "LINK",
                        "LTC",
                        "M",
                        "MNT",
                        "MORPHO",
                        "NEAR",
                        "OKB",
                        "ONDO",
                        "PEPE",
                        "SHIB",
                        "SKY",
                        "SOL",
                        "SUI",
                        "TAO",
                        "TON",
                        "TRX",
                        "UNI",
                        "WLFI",
                        "XLM",
                        "XMR",
                        "XRP",
                        "ZEC",
                    ],
                    "short": [
                        "AAVE",
                        "ADA",
                        "ASTER",
                        "AVAX",
                        "BCH",
                        "BNB",
                        "BTC",
                        "CC",
                        "CRO",
                        "DOGE",
                        "DOT",
                        "ETC",
                        "ETH",
                        "HBAR",
                        "HYPE",
                        "ICP",
                        "LINK",
                        "LTC",
                        "M",
                        "MNT",
                        "MORPHO",
                        "NEAR",
                        "OKB",
                        "ONDO",
                        "PEPE",
                        "SHIB",
                        "SKY",
                        "SOL",
                        "SUI",
                        "TAO",
                        "TON",
                        "TRX",
                        "UNI",
                        "WLFI",
                        "XLM",
                        "XMR",
                        "XRP",
                        "ZEC",
                    ],
                },
                "auto_gs": True,
                "balance_hysteresis_snap_pct": 0.01,
                "balance_override": None,
                "candle_lock_timeout_seconds": 10,
                "custom_endpoints_path": None,
                "defer_broad_candle_warmup": True,
                "enable_archive_candle_fetch": False,
                "execution_delay_seconds": 2,
                "fee_conversion_max_age_ms": 86400000,
                "fee_pct_fallback": 0.0002,
                "fee_pct_sanity_abs_max": 0.001,
                "filter_by_min_effective_cost": True,
                "fills_confirmation_overlap_minutes": 60.0,
                "fills_recent_overlap_minutes": 10.0,
                "forced_mode_long": "",
                "forced_mode_short": "",
                "hedge_mode": False,
                "hsl_position_during_cooldown_policy": "panic",
                "hsl_signal_mode": "unified",
                "ignored_coins": {"long": [], "short": []},
                "inactive_coin_candle_ttl_minutes": 10,
                "leverage": 10,
                "margin_mode_preference": "cross",
                "market_snapshot_ticker_strategy": "auto",
                "market_order_near_touch_threshold": 0.001,
                "market_orders_allowed": False,
                "max_concurrent_api_requests": None,
                "max_disk_candles_per_symbol_per_tf": 2000000,
                "max_memory_candles_per_symbol": 200000,
                "max_active_candle_tail_gap_minutes": 10,
                "max_n_cancellations_per_batch": 5,
                "max_n_creations_per_batch": 3,
                "max_n_restarts_per_day": 10,
                "max_forager_candle_staleness_minutes": None,
                "max_forager_candle_refresh_seconds": 45,
                "max_ohlcv_fetches_per_minute": 30,
                "max_realized_loss_pct": 1.0,
                "max_warmup_minutes": 0,
                "minimum_coin_age_days": 60,
                "forager_score_hysteresis_pct": 0.02,
                "initial_entry_exec_max_market_dist_pct": 0.005,
                "order_match_tolerance_pct": 0.0002,
                "pnls_max_lookback_days": 30,
                "recv_window_ms": 5000,
                "strategy_kind": DEFAULT_STRATEGY_KIND,
                "time_in_force": "good_till_cancelled",
                "user": "bybit_01",
                "warmup_concurrency": 0,
                "warmup_jitter_seconds": 30,
                "warmup_ratio": 0.3,
            },
            "logging": {
                "backup_count": 5,
                "dir": "logs",
                "level": 1,
                "max_bytes_mb": 10.0,
                "memory_snapshot_interval_minutes": 30,
                "persist_to_file": True,
                "rotation": False,
                "volume_refresh_info_threshold_seconds": 30,
            },
            "monitor": {
                "checkpoint_interval_minutes": 10.0,
                "compress_rotated_segments": True,
                "emit_completed_candles": True,
                "enabled": True,
                "event_rotation_mb": 128.0,
                "event_rotation_minutes": 60.0,
                "include_raw_fill_payloads": False,
                "max_total_bytes": 1073741824,
                "price_tick_min_interval_ms": 500,
                "retain_candles": True,
                "retain_days": 7.0,
                "retain_fills": True,
                "retain_price_ticks": True,
                "root_dir": "monitor",
                "snapshot_interval_seconds": 1.0,
            },
            "optimize": {
                "bounds": get_optimize_bounds_defaults(),
                "backend": "pymoo",
                "compress_results_file": True,
                "enable_overrides": [],
                "fixed_params": [],
                "fixed_runtime_overrides": {
                    "bot.long.hsl.no_restart_drawdown_threshold": 1,
                    "bot.short.hsl.no_restart_drawdown_threshold": 1,
                },
                "iters": 500000,
                "limits": [
                    {
                        "metric": "drawdown_worst_strategy_eq",
                        "penalize_if": "greater_than",
                        "value": 0.8,
                        "enabled": False,
                    },
                    {
                        "metric": "drawdown_worst_mean_1pct_strategy_eq",
                        "penalize_if": "greater_than",
                        "value": 0.6,
                        "enabled": False,
                    },
                    {
                        "metric": "loss_profit_ratio",
                        "penalize_if": "greater_than",
                        "value": 0.85,
                        "enabled": False,
                    },
                    {
                        "metric": "backtest_completion_ratio",
                        "penalize_if": "less_than",
                        "value": 0.99,
                        "enabled": True,
                    },
                    {
                        "metric": "high_exposure_days_max_long",
                        "penalize_if": "greater_than",
                        "value": 90,
                        "enabled": False,
                    },
                    {
                        "metric": "position_held_days_max",
                        "penalize_if": "greater_than",
                        "value": 90,
                        "enabled": False,
                    },
                    {
                        "metric": "strategy_eq_recovery_days_max",
                        "penalize_if": "greater_than",
                        "value": 90,
                        "enabled": False,
                    },
                    {
                        "metric": "hard_stop_restarts_per_year",
                        "penalize_if": "less_than",
                        "value": 0.1,
                        "enabled": False,
                    },
                    {
                        "metric": "adg_strategy_eq",
                        "penalize_if": "less_than_or_equal",
                        "value": 0.0012,
                        "enabled": False,
                    },
                    {
                        "metric": "strategy_eq_recovery_days_max",
                        "penalize_if": "greater_than_or_equal",
                        "value": 71,
                        "enabled": False,
                    },
                    {
                        "metric": "drawdown_worst_strategy_eq",
                        "penalize_if": "greater_than_or_equal",
                        "value": 0.58,
                        "enabled": False,
                    },
                    {
                        "metric": "position_held_days_max",
                        "penalize_if": "greater_than_or_equal",
                        "value": 100,
                        "enabled": False,
                    },
                    {
                        "metric": "fills_gap_p95_hours",
                        "penalize_if": "greater_than_or_equal",
                        "value": 72,
                        "enabled": False,
                    },
                    {
                        "metric": "adg_strategy_eq",
                        "penalize_if": "less_than_or_equal",
                        "value": 0.0025,
                    },
                    {
                        "metric": "adg_strategy_eq_w",
                        "penalize_if": "less_than_or_equal",
                        "value": 0.00225,
                    },
                    {
                        "metric": "strategy_eq_recovery_days_max",
                        "penalize_if": "greater_than_or_equal",
                        "value": 150,
                    },
                    {
                        "metric": "position_held_days_max",
                        "penalize_if": "greater_than_or_equal",
                        "value": 14,
                    },
                    {
                        "metric": "fills_gap_p95_hours",
                        "penalize_if": "greater_than_or_equal",
                        "value": 6,
                    },
                    {
                        "metric": "drawdown_worst_strategy_eq",
                        "penalize_if": "greater_than_or_equal",
                        "value": 0.57,
                    },
                ],
                "n_cpus": 8,
                "pareto_max_size": 1000,
                "population_size": None,
                "pymoo": {
                    "algorithm": "auto",
                    "shared": {
                        "crossover_eta": 20,
                        "crossover_prob_var": 0.5,
                        "eliminate_duplicates": True,
                        "mutation_eta": 20,
                        "mutation_prob_var": "auto",
                    },
                    "algorithms": {
                        "nsga2": {},
                        "nsga3": {
                            "ref_dirs": {
                                "method": "das_dennis",
                                "n_partitions": "auto",
                            }
                        },
                    },
                },
                "round_to_n_significant_digits": 3,
                "scoring": [
                    {"metric": "adg_strategy_eq", "goal": "max"},
                    {"metric": "adg_strategy_eq_w", "goal": "max"},
                    {"metric": "mdg_strategy_eq", "goal": "max"},
                    {"metric": "sortino_ratio_strategy_eq", "goal": "max"},
                    {"metric": "strategy_eq_recovery_days_max", "goal": "min"},
                    {"metric": "position_held_days_max", "goal": "min"},
                    {"metric": "drawdown_worst_strategy_eq", "goal": "min"},
                    {"metric": "drawdown_worst_mean_1pct_strategy_eq", "goal": "min"},
                    {"metric": "fills_gap_p95_hours", "goal": "min"},
                ],
                "write_all_results": True,
                "crossover_eta": 20,
                "crossover_probability": 0.64,
                "mutation_eta": 20,
                "mutation_indpb": 0.0135135135,
                "mutation_probability": 0.34,
                "offspring_multiplier": 1,
            },
        }
    )
