from copy import deepcopy

from .optimize_bounds import get_optimize_bounds_defaults
from .strategy import DEFAULT_STRATEGY_KIND, get_all_strategy_defaults


DEFAULT_EXAMPLE_CONFIG_PATH = "configs/examples/default_trailing_grid_long_npos10.json"


def _get_shared_bot_defaults():
    return {
        "long": {
            "risk": {
                "n_positions": 10,
                "total_wallet_exposure_limit": 1.25,
                "twel_enforcer_threshold": 1,
                "we_excess_allowance_pct": 0.37,
                "wel_enforcer_threshold": 0.994,
            },
            "forager": {
                "score_weights": {
                    "ema_readiness": 0.0,
                    "volatility": 1.0,
                    "volume": 0.0,
                },
                "volatility_ema_span": 225,
                "volume_drop_pct": 0.57,
                "volume_ema_span": 520,
            },
            "hsl": {
                "cooldown_minutes_after_red": 0,
                "ema_span_minutes": 60,
                "enabled": False,
                "no_restart_drawdown_threshold": 1,
                "orange_tier_mode": "tp_only_with_active_entry_cancellation",
                "panic_close_order_type": "limit",
                "red_threshold": 0.2,
                "tier_ratios": {"orange": 0.75, "yellow": 0.5},
            },
            "unstuck": {
                "close_pct": 0.078,
                "ema_dist": -0.07,
                "loss_allowance_pct": 0.0102,
                "threshold": 0.408,
            },
        },
        "short": {
            "risk": {
                "n_positions": 10,
                "total_wallet_exposure_limit": 0,
                "twel_enforcer_threshold": 0.95,
                "we_excess_allowance_pct": 0,
                "wel_enforcer_threshold": 0.95,
            },
            "forager": {
                "score_weights": {
                    "ema_readiness": 0.0,
                    "volatility": 1.0,
                    "volume": 0.0,
                },
                "volatility_ema_span": 10,
                "volume_drop_pct": 0.5,
                "volume_ema_span": 360,
            },
            "hsl": {
                "cooldown_minutes_after_red": 0,
                "ema_span_minutes": 60,
                "enabled": False,
                "no_restart_drawdown_threshold": 1,
                "orange_tier_mode": "tp_only_with_active_entry_cancellation",
                "panic_close_order_type": "limit",
                "red_threshold": 0.2,
                "tier_ratios": {"orange": 0.75, "yellow": 0.5},
            },
            "unstuck": {
                "close_pct": 0.05,
                "ema_dist": -0.2,
                "loss_allowance_pct": 0.01,
                "threshold": 0.4,
            },
        },
    }


def get_template_config():
    return deepcopy(
        {
            "backtest": {
                "aggregate": {
                    "default": "mean",
                    "peak_recovery_hours_hsl": "max",
                    "position_held_hours_max": "max",
                    "drawdown_worst_hsl": "max",
                    "drawdown_worst_mean_1pct_hsl": "max",
                },
                "balance_sample_divider": 60,
                "base_dir": "backtests",
                "btc_collateral_cap": 0.0,
                "btc_collateral_ltv_cap": None,
                "candle_interval_minutes": 1,
                "coin_sources": {},
                "compress_cache": True,
                "dynamic_wel_by_tradability": True,
                "end_date": "now",
                "exchanges": ["binance", "bybit"],
                "filter_by_min_effective_cost": False,
                "gap_tolerance_ohlcvs_minutes": 120,
                "liquidation_threshold": 0.05,
                "maker_fee_override": 0.0004,
                "market_settings_sources": {},
                "max_warmup_minutes": 0,
                "ohlcv_source_dir": None,
                "market_order_slippage_pct": 0.0005,
                "scenarios": [
                    {"label": "base"},
                    {
                        "coins": [
                            "BTC",
                            "ETH",
                            "XRP",
                            "BNB",
                            "SOL",
                            "TRX",
                            "DOGE",
                            "ADA",
                            "BCH",
                            "HYPE",
                            "LINK",
                        ],
                        "label": "subset_1_top",
                    },
                    {
                        "coins": [
                            "XMR",
                            "XLM",
                            "CC",
                            "LTC",
                            "AVAX",
                            "HBAR",
                            "ZEC",
                            "SUI",
                            "SHIB",
                            "CRO",
                            "TON",
                            "M",
                        ],
                        "label": "subset_2_mid",
                    },
                    {
                        "coins": [
                            "TAO",
                            "XAUT",
                            "DOT",
                            "WLFI",
                            "MNT",
                            "PAXG",
                            "UNI",
                            "OKB",
                            "NEAR",
                            "AAVE",
                            "ASTER",
                        ],
                        "label": "subset_3_bottom",
                    },
                    {
                        "coins": [
                            "BTC",
                            "BNB",
                            "DOGE",
                            "HYPE",
                            "XLM",
                            "AVAX",
                            "SUI",
                            "TON",
                            "XAUT",
                            "MNT",
                            "OKB",
                            "ASTER",
                        ],
                        "label": "subset_4_mix",
                    },
                    {
                        "coins": [
                            "ETH",
                            "SOL",
                            "ADA",
                            "LINK",
                            "CC",
                            "HBAR",
                            "SHIB",
                            "M",
                            "DOT",
                            "PAXG",
                            "NEAR",
                        ],
                        "label": "subset_5_mix",
                    },
                    {
                        "coins": [
                            "XRP",
                            "TRX",
                            "BCH",
                            "XMR",
                            "LTC",
                            "ZEC",
                            "CRO",
                            "TAO",
                            "WLFI",
                            "UNI",
                            "AAVE",
                        ],
                        "label": "subset_6_mix",
                    },
                    {
                        "label": "n_positions_3",
                        "overrides": {"bot.long.risk.n_positions": 3, "bot.short.risk.n_positions": 3},
                    },
                    {
                        "label": "n_positions_20",
                        "overrides": {"bot.long.risk.n_positions": 20, "bot.short.risk.n_positions": 20},
                    },
                    {
                        "label": "btc_collateral_cap=0.5",
                        "overrides": {"backtest.btc_collateral_cap": 0.5},
                    },
                    {
                        "label": "twel=2",
                        "overrides": {"bot.long.risk.total_wallet_exposure_limit": 2},
                    },
                ],
                "start_date": "2021-01-01",
                "starting_balance": 100000,
                "suite_enabled": False,
                "taker_fee_override": None,
                "volume_normalization": True,
            },
            "bot": {
                "long": {
                    **deepcopy(_get_shared_bot_defaults()["long"]),
                    "strategy": get_all_strategy_defaults()["long"],
                },
                "short": {
                    **deepcopy(_get_shared_bot_defaults()["short"]),
                    "strategy": get_all_strategy_defaults()["short"],
                },
            },
            "coin_overrides": {},
            "live": {
                "approved_coins": {
                    "long": [
                        "BTC",
                        "ETH",
                        "XRP",
                        "BNB",
                        "SOL",
                        "TRX",
                        "BCH",
                        "ADA",
                        "HYPE",
                        "LINK",
                        "XMR",
                        "XLM",
                        "HBAR",
                        "LTC",
                        "AVAX",
                        "SUI",
                        "TON",
                        "XAUT",
                        "UNI",
                        "DOT",
                    ],
                    "short": [
                        "BTC",
                        "ETH",
                        "XRP",
                        "BNB",
                        "SOL",
                        "TRX",
                        "BCH",
                        "ADA",
                        "HYPE",
                        "LINK",
                        "XMR",
                        "XLM",
                        "HBAR",
                        "LTC",
                        "AVAX",
                        "SUI",
                        "TON",
                        "XAUT",
                        "UNI",
                        "DOT",
                    ],
                },
                "auto_gs": True,
                "balance_hysteresis_snap_pct": 0.01,
                "balance_override": None,
                "candle_lock_timeout_seconds": 10,
                "empty_means_all_approved": False,
                "enable_archive_candle_fetch": False,
                "execution_delay_seconds": 2,
                "filter_by_min_effective_cost": True,
                "forced_mode_long": "",
                "forced_mode_short": "",
                "hedge_mode": False,
                "hsl_position_during_cooldown_policy": "panic",
                "hsl_signal_mode": "unified",
                "ignored_coins": {"long": [], "short": []},
                "inactive_coin_candle_ttl_minutes": 10,
                "leverage": 10,
                "margin_mode_preference": "cross",
                "market_order_near_touch_threshold": 0.001,
                "market_orders_allowed": False,
                "max_concurrent_api_requests": None,
                "max_disk_candles_per_symbol_per_tf": 2000000,
                "max_memory_candles_per_symbol": 200000,
                "max_n_cancellations_per_batch": 5,
                "max_n_creations_per_batch": 3,
                "max_n_restarts_per_day": 10,
                "max_ohlcv_fetches_per_minute": 30,
                "max_realized_loss_pct": 1.0,
                "max_warmup_minutes": 0,
                "minimum_coin_age_days": 365,
                "order_match_tolerance_pct": 0.0002,
                "pnls_max_lookback_days": 30,
                "price_distance_threshold": 0.002,
                "recv_window_ms": 5000,
                "strategy_kind": DEFAULT_STRATEGY_KIND,
                "time_in_force": "good_till_cancelled",
                "user": "bybit_01",
                "warmup_concurrency": 0,
                "warmup_jitter_seconds": 30,
                "warmup_ratio": 0.3,
            },
            "logging": {
                "level": 1,
                "memory_snapshot_interval_minutes": 30,
                "volume_refresh_info_threshold_seconds": 30,
            },
            "monitor": {
                "checkpoint_interval_minutes": 10.0,
                "compress_rotated_segments": True,
                "emit_completed_candles": True,
                "enabled": True,
                "event_rotation_mb": 128.0,
                "event_rotation_minutes": 60.0,
                "include_raw_fill_payloads": False,
                "max_total_bytes": 1073741824,
                "price_tick_min_interval_ms": 500,
                "retain_candles": True,
                "retain_days": 7.0,
                "retain_fills": True,
                "retain_price_ticks": True,
                "root_dir": "monitor",
                "snapshot_interval_seconds": 1.0,
            },
            "optimize": {
                "bounds": get_optimize_bounds_defaults(),
                "backend": "pymoo",
                "compress_results_file": True,
                "enable_overrides": [],
                "fixed_params": [],
                "fixed_runtime_overrides": {
                    "bot.long.hsl_no_restart_drawdown_threshold": 1,
                    "bot.short.hsl_no_restart_drawdown_threshold": 1,
                },
                "iters": 500000,
                "limits": [
                    {
                        "metric": "drawdown_worst_hsl",
                        "penalize_if": "greater_than",
                        "value": 0.8,
                        "enabled": False,
                    },
                    {
                        "metric": "drawdown_worst_mean_1pct_hsl",
                        "penalize_if": "greater_than",
                        "value": 0.6,
                        "enabled": False,
                    },
                    {
                        "metric": "loss_profit_ratio",
                        "penalize_if": "greater_than",
                        "value": 0.85,
                        "enabled": False,
                    },
                    {
                        "metric": "backtest_completion_ratio",
                        "penalize_if": "less_than",
                        "value": 0.99,
                        "enabled": True,
                    },
                    {
                        "metric": "high_exposure_hours_max_long",
                        "penalize_if": "greater_than",
                        "value": 2160,
                        "enabled": False,
                    },
                    {
                        "metric": "position_held_hours_max",
                        "penalize_if": "greater_than",
                        "value": 2160,
                        "enabled": False,
                    },
                    {
                        "metric": "peak_recovery_hours_hsl",
                        "penalize_if": "greater_than",
                        "value": 2160,
                        "enabled": False,
                    },
                    {
                        "metric": "hard_stop_restarts_per_year",
                        "penalize_if": "less_than",
                        "value": 0.1,
                        "enabled": False,
                    },
                ],
                "n_cpus": 6,
                "pareto_max_size": 1000,
                "population_size": None,
                "pymoo": {
                    "algorithm": "auto",
                    "shared": {
                        "crossover_eta": 20,
                        "crossover_prob_var": 0.5,
                        "eliminate_duplicates": True,
                        "mutation_eta": 20,
                        "mutation_prob_var": "auto",
                    },
                    "algorithms": {
                        "nsga2": {},
                        "nsga3": {
                            "ref_dirs": {
                                "method": "das_dennis",
                                "n_partitions": "auto",
                            }
                        },
                    },
                },
                "round_to_n_significant_digits": 3,
                "scoring": [
                    {"metric": "adg_strategy_pnl_rebased", "goal": "max"},
                    {"metric": "adg_strategy_pnl_rebased_w", "goal": "max"},
                    {"metric": "mdg_strategy_pnl_rebased", "goal": "max"},
                    {"metric": "mdg_strategy_pnl_rebased_w", "goal": "max"},
                    {"metric": "peak_recovery_hours_hsl", "goal": "min"},
                    {"metric": "position_held_hours_max", "goal": "min"},
                    {"metric": "drawdown_worst_hsl", "goal": "min"},
                    {"metric": "drawdown_worst_mean_1pct_hsl", "goal": "min"},
                ],
                "write_all_results": True,
                "crossover_eta": 20,
                "crossover_probability": 0.64,
                "mutation_eta": 20,
                "mutation_indpb": 0.0135135135,
                "mutation_probability": 0.34,
                "offspring_multiplier": 1,
            },
        }
    )
