from copy import deepcopy


DEFAULT_EXAMPLE_CONFIG_PATH = "configs/examples/forager_long_only.json"


def get_template_config():
    return deepcopy(
        {
            "backtest": {
                "aggregate": {"default": "mean"},
                "balance_sample_divider": 60,
                "base_dir": "backtests",
                "btc_collateral_cap": 1.0,
                "btc_collateral_ltv_cap": None,
                "compress_cache": True,
                "coin_sources": {},
                "ohlcv_source_dir": None,
                "market_settings_sources": {},
                "end_date": "now",
                "exchanges": ["binance", "bybit", "gateio", "bitget"],
                "filter_by_min_effective_cost": None,
                "dynamic_wel_by_tradability": True,
                "candle_interval_minutes": 1,
                "gap_tolerance_ohlcvs_minutes": 120.0,
                "liquidation_threshold": 0.05,
                "maker_fee_override": None,
                "panic_market_slippage_pct": 0.0005,
                "taker_fee_override": None,
                "max_warmup_minutes": 0.0,
                "scenarios": [],
                "start_date": "2021-04-01",
                "starting_balance": 100000.0,
                "suite_enabled": True,
                "volume_normalization": True,
            },
            "bot": {
                "long": {
                    "close_grid_markup_end": 0.0089,
                    "close_grid_markup_start": 0.0344,
                    "close_grid_qty_pct": 0.125,
                    "close_trailing_grid_ratio": 0.5,
                    "close_trailing_qty_pct": 0.125,
                    "close_trailing_retracement_pct": 0.002,
                    "close_trailing_threshold_pct": 0.008,
                    "ema_span_0": 1318.0,
                    "ema_span_1": 1435.0,
                    "hsl_cooldown_minutes_after_red": 0.0,
                    "hsl_ema_span_minutes": 60.0,
                    "hsl_enabled": False,
                    "hsl_no_restart_drawdown_threshold": 1.0,
                    "hsl_orange_tier_mode": "tp_only_with_active_entry_cancellation",
                    "hsl_panic_close_order_type": "market",
                    "hsl_red_threshold": 0.25,
                    "hsl_tier_ratios": {"yellow": 0.5, "orange": 0.75},
                    "entry_grid_double_down_factor": 0.894,
                    "entry_grid_spacing_pct": 0.04,
                    "entry_grid_spacing_volatility_weight": 0.0,
                    "entry_grid_spacing_we_weight": 0.697,
                    "entry_initial_ema_dist": -0.00738,
                    "entry_initial_qty_pct": 0.00592,
                    "entry_trailing_double_down_factor": 0.894,
                    "entry_trailing_grid_ratio": 0.5,
                    "entry_trailing_retracement_pct": 0.01,
                    "entry_trailing_retracement_volatility_weight": 0.0,
                    "entry_trailing_retracement_we_weight": 0.0,
                    "entry_trailing_threshold_pct": 0.05,
                    "entry_trailing_threshold_volatility_weight": 0.0,
                    "entry_trailing_threshold_we_weight": 0.0,
                    "entry_volatility_ema_span_hours": 72,
                    "forager_volatility_ema_span": 60.0,
                    "forager_volume_ema_span": 60.0,
                    "forager_volume_drop_pct": 0.95,
                    "forager_score_weights": {
                        "volume": 0.0,
                        "ema_readiness": 0.0,
                        "volatility": 1.0,
                    },
                    "n_positions": 10.0,
                    "risk_twel_enforcer_threshold": 1.0,
                    "risk_we_excess_allowance_pct": 0.0,
                    "risk_wel_enforcer_threshold": 1.0,
                    "total_wallet_exposure_limit": 1.7,
                    "unstuck_close_pct": 0.001,
                    "unstuck_ema_dist": 0.0,
                    "unstuck_loss_allowance_pct": 0.03,
                    "unstuck_threshold": 0.916,
                },
                "short": {
                    "close_grid_markup_end": 0.0089,
                    "close_grid_markup_start": 0.0344,
                    "close_grid_qty_pct": 0.125,
                    "close_trailing_grid_ratio": 0.5,
                    "close_trailing_qty_pct": 0.125,
                    "close_trailing_retracement_pct": 0.002,
                    "close_trailing_threshold_pct": 0.008,
                    "ema_span_0": 1318.0,
                    "ema_span_1": 1435.0,
                    "hsl_cooldown_minutes_after_red": 0.0,
                    "hsl_ema_span_minutes": 60.0,
                    "hsl_enabled": False,
                    "hsl_no_restart_drawdown_threshold": 1.0,
                    "hsl_orange_tier_mode": "tp_only_with_active_entry_cancellation",
                    "hsl_panic_close_order_type": "market",
                    "hsl_red_threshold": 0.25,
                    "hsl_tier_ratios": {"yellow": 0.5, "orange": 0.75},
                    "entry_grid_double_down_factor": 0.894,
                    "entry_grid_spacing_pct": 0.04,
                    "entry_grid_spacing_volatility_weight": 0.0,
                    "entry_grid_spacing_we_weight": 0.697,
                    "entry_initial_ema_dist": -0.00738,
                    "entry_initial_qty_pct": 0.00592,
                    "entry_trailing_double_down_factor": 0.894,
                    "entry_trailing_grid_ratio": 0.5,
                    "entry_trailing_retracement_pct": 0.01,
                    "entry_trailing_retracement_volatility_weight": 0.0,
                    "entry_trailing_retracement_we_weight": 0.0,
                    "entry_trailing_threshold_pct": 0.05,
                    "entry_trailing_threshold_volatility_weight": 0.0,
                    "entry_trailing_threshold_we_weight": 0.0,
                    "entry_volatility_ema_span_hours": 72,
                    "forager_volatility_ema_span": 60.0,
                    "forager_volume_ema_span": 60.0,
                    "forager_volume_drop_pct": 0.95,
                    "forager_score_weights": {
                        "volume": 0.0,
                        "ema_readiness": 0.0,
                        "volatility": 1.0,
                    },
                    "n_positions": 10.0,
                    "risk_twel_enforcer_threshold": 1.0,
                    "risk_we_excess_allowance_pct": 0.0,
                    "risk_wel_enforcer_threshold": 1.0,
                    "total_wallet_exposure_limit": 1.7,
                    "unstuck_close_pct": 0.001,
                    "unstuck_ema_dist": 0.0,
                    "unstuck_loss_allowance_pct": 0.03,
                    "unstuck_threshold": 0.916,
                },
            },
            "coin_overrides": {},
            "live": {
                "approved_coins": {"long": [], "short": []},
                "auto_gs": True,
                "balance_hysteresis_snap_pct": 0.02,
                "balance_override": None,
                "candle_lock_timeout_seconds": 10.0,
                "empty_means_all_approved": False,
                "enable_archive_candle_fetch": False,
                "execution_delay_seconds": 2.0,
                "filter_by_min_effective_cost": True,
                "forced_mode_long": "",
                "forced_mode_short": "",
                "hedge_mode": True,
                "hsl_position_during_cooldown_policy": "panic",
                "hsl_signal_mode": "pside",
                "ignored_coins": {"long": [], "short": []},
                "inactive_coin_candle_ttl_minutes": 10.0,
                "leverage": 10.0,
                "margin_mode_preference": "cross",
                "market_orders_allowed": True,
                "max_disk_candles_per_symbol_per_tf": 2000000,
                "max_memory_candles_per_symbol": 20000,
                "max_n_cancellations_per_batch": 5,
                "max_n_creations_per_batch": 3,
                "max_n_restarts_per_day": 10,
                "max_ohlcv_fetches_per_minute": 30,
                "max_realized_loss_pct": 1.0,
                "max_warmup_minutes": 0.0,
                "market_order_near_touch_threshold": 0.001,
                "minimum_coin_age_days": 7.0,
                "order_match_tolerance_pct": 0.0002,
                "pnls_max_lookback_days": 30.0,
                "price_distance_threshold": 0.002,
                "recv_window_ms": 5000,
                "time_in_force": "good_till_cancelled",
                "user": "bybit_01",
                "warmup_jitter_seconds": 30.0,
                "warmup_ratio": 0.2,
                "warmup_concurrency": 0,
                "max_concurrent_api_requests": None,
            },
            "logging": {
                "level": 1,
                "memory_snapshot_interval_minutes": 30.0,
                "volume_refresh_info_threshold_seconds": 30.0,
            },
            "monitor": {
                "enabled": True,
                "root_dir": "monitor",
                "snapshot_interval_seconds": 1.0,
                "checkpoint_interval_minutes": 10.0,
                "event_rotation_mb": 128.0,
                "event_rotation_minutes": 60.0,
                "retain_days": 7.0,
                "max_total_bytes": 1073741824,
                "retain_price_ticks": True,
                "retain_candles": True,
                "retain_fills": True,
                "compress_rotated_segments": True,
                "price_tick_min_interval_ms": 500,
                "emit_completed_candles": True,
                "include_raw_fill_payloads": False,
            },
            "optimize": {
                "bounds": {
                    "long_hsl_cooldown_minutes_after_red": [0.0, 0.0],
                    "long_hsl_ema_span_minutes": [60.0, 60.0],
                    "long_hsl_red_threshold": [0.25, 0.25],
                    "long_close_grid_markup_end": [0.001, 0.03],
                    "long_close_grid_markup_start": [0.001, 0.03],
                    "long_close_grid_qty_pct": [0.05, 1.0],
                    "long_close_trailing_grid_ratio": [-1.0, 1.0],
                    "long_close_trailing_qty_pct": [0.05, 1.0],
                    "long_close_trailing_retracement_pct": [0.001, 0.1],
                    "long_close_trailing_threshold_pct": [0.001, 0.1],
                    "long_ema_span_0": [200.0, 1440.0],
                    "long_ema_span_1": [200.0, 1440.0],
                    "long_entry_grid_double_down_factor": [0.1, 3.0],
                    "long_entry_grid_spacing_pct": [0.005, 0.12],
                    "long_entry_grid_spacing_volatility_weight": [0.0, 400.0],
                    "long_entry_grid_spacing_we_weight": [0.0, 20.0],
                    "long_entry_initial_ema_dist": [-0.1, 0.002],
                    "long_entry_initial_qty_pct": [0.005, 0.1],
                    "long_entry_trailing_double_down_factor": [0.1, 3.0],
                    "long_entry_trailing_grid_ratio": [-1.0, 1.0],
                    "long_entry_trailing_retracement_pct": [0.001, 0.1],
                    "long_entry_trailing_retracement_volatility_weight": [0.0, 400.0],
                    "long_entry_trailing_retracement_we_weight": [0.0, 20.0],
                    "long_entry_trailing_threshold_pct": [0.001, 0.1],
                    "long_entry_trailing_threshold_volatility_weight": [0.0, 400.0],
                    "long_entry_trailing_threshold_we_weight": [0.0, 20.0],
                    "long_entry_volatility_ema_span_hours": [24.0, 336.0],
                    "long_forager_volatility_ema_span": [10.0, 1440.0],
                    "long_forager_volume_ema_span": [10.0, 1440.0],
                    "long_forager_volume_drop_pct": [0.0, 1.0],
                    "long_forager_score_weights_volume": [0.0, 1.0],
                    "long_forager_score_weights_ema_readiness": [0.0, 1.0],
                    "long_forager_score_weights_volatility": [0.0, 1.0],
                    "long_n_positions": [1.0, 20.0],
                    "long_risk_twel_enforcer_threshold": [0.9, 1.01],
                    "long_risk_we_excess_allowance_pct": [0.0, 0.5],
                    "long_risk_wel_enforcer_threshold": [0.8, 1.05],
                    "long_total_wallet_exposure_limit": [0.0, 2.0],
                    "long_unstuck_close_pct": [0.001, 0.1],
                    "long_unstuck_ema_dist": [-0.1, 0.01],
                    "long_unstuck_loss_allowance_pct": [0.001, 0.05],
                    "long_unstuck_threshold": [0.4, 0.95],
                    "short_close_grid_markup_end": [0.001, 0.03],
                    "short_close_grid_markup_start": [0.001, 0.03],
                    "short_close_grid_qty_pct": [0.05, 1.0],
                    "short_close_trailing_grid_ratio": [-1.0, 1.0],
                    "short_close_trailing_qty_pct": [0.05, 1.0],
                    "short_close_trailing_retracement_pct": [0.001, 0.1],
                    "short_close_trailing_threshold_pct": [0.001, 0.1],
                    "short_ema_span_0": [200.0, 1440.0],
                    "short_ema_span_1": [200.0, 1440.0],
                    "short_entry_grid_double_down_factor": [0.1, 3.0],
                    "short_entry_grid_spacing_pct": [0.005, 0.12],
                    "short_entry_grid_spacing_volatility_weight": [0.0, 400.0],
                    "short_entry_grid_spacing_we_weight": [0.0, 20.0],
                    "short_entry_initial_ema_dist": [-0.1, 0.002],
                    "short_entry_initial_qty_pct": [0.005, 0.1],
                    "short_entry_trailing_double_down_factor": [0.1, 3.0],
                    "short_entry_trailing_grid_ratio": [-1.0, 1.0],
                    "short_entry_trailing_retracement_pct": [0.001, 0.1],
                    "short_entry_trailing_retracement_volatility_weight": [0.0, 400.0],
                    "short_entry_trailing_retracement_we_weight": [0.0, 20.0],
                    "short_entry_trailing_threshold_pct": [0.001, 0.1],
                    "short_entry_trailing_threshold_volatility_weight": [0.0, 400.0],
                    "short_entry_trailing_threshold_we_weight": [0.0, 20.0],
                    "short_entry_volatility_ema_span_hours": [24.0, 336.0],
                    "short_forager_volatility_ema_span": [10.0, 1440.0],
                    "short_forager_volume_ema_span": [10.0, 1440.0],
                    "short_forager_volume_drop_pct": [0.0, 1.0],
                    "short_forager_score_weights_volume": [0.0, 1.0],
                    "short_forager_score_weights_ema_readiness": [0.0, 1.0],
                    "short_forager_score_weights_volatility": [0.0, 1.0],
                    "short_hsl_cooldown_minutes_after_red": [0.0, 0.0],
                    "short_hsl_ema_span_minutes": [60.0, 60.0],
                    "short_hsl_red_threshold": [0.25, 0.25],
                    "short_n_positions": [1.0, 20.0],
                    "short_risk_twel_enforcer_threshold": [0.9, 1.01],
                    "short_risk_we_excess_allowance_pct": [0.0, 0.5],
                    "short_risk_wel_enforcer_threshold": [0.8, 1.05],
                    "short_total_wallet_exposure_limit": [0.0, 2.0],
                    "short_unstuck_close_pct": [0.001, 0.1],
                    "short_unstuck_ema_dist": [-0.1, 0.01],
                    "short_unstuck_loss_allowance_pct": [0.001, 0.05],
                    "short_unstuck_threshold": [0.4, 0.95],
                },
                "backend": "pymoo",
                "compress_results_file": True,
                "crossover_eta": 20.0,
                "crossover_probability": 0.64,
                "enable_overrides": [],
                "fixed_params": [],
                "iters": 30000,
                "limits": [
                    {
                        "metric": "drawdown_worst_usd",
                        "penalize_if": "greater_than",
                        "value": 0.85,
                        "enabled": True,
                    },
                    {
                        "metric": "loss_profit_ratio",
                        "penalize_if": "greater_than",
                        "value": 0.85,
                        "enabled": True,
                    },
                    {
                        "metric": "adg_pnl",
                        "penalize_if": "less_than",
                        "stat": "mean",
                        "value": 0,
                        "enabled": False,
                    },
                    {
                        "metric": "peak_recovery_hours_pnl",
                        "penalize_if": "greater_than",
                        "value": 1680,
                        "enabled": False,
                    },
                    {
                        "metric": "position_held_hours_max",
                        "penalize_if": "greater_than",
                        "value": 840,
                        "enabled": False,
                    },
                ],
                "mutation_eta": 20.0,
                "mutation_indpb": 0.0,
                "mutation_probability": 0.34,
                "n_cpus": 5,
                "offspring_multiplier": 1.0,
                "pareto_max_size": 1000,
                "population_size": None,
                "pymoo": {
                    "algorithm": "auto",
                    "shared": {
                        "crossover_eta": 20.0,
                        "crossover_prob_var": 0.5,
                        "eliminate_duplicates": True,
                        "mutation_eta": 20.0,
                        "mutation_prob_var": "auto",
                    },
                    "algorithms": {
                        "nsga2": {},
                        "nsga3": {
                            "ref_dirs": {
                                "method": "das_dennis",
                                "n_partitions": "auto",
                            }
                        },
                    },
                },
                "fixed_runtime_overrides": {
                    "bot.long.hsl_no_restart_drawdown_threshold": 1.0,
                    "bot.short.hsl_no_restart_drawdown_threshold": 1.0,
                },
                "round_to_n_significant_digits": 5,
                "scoring": ["adg", "sharpe_ratio"],
                "write_all_results": True,
            },
        }
    )
