name: Deploy Passivbot Configs

on:
  push:
    paths:
      - 'configs/live/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy new config to VM
      run: |
        scp -o StrictHostKeyChecking=no -r configs/live/* manhngodh@35.229.225.235:/opt/passivbot/configs/live/
        ssh -o StrictHostKeyChecking=no manhngodh@35.229.225.235 'sudo bash /opt/passivbot/update_supervisor_configs.sh'
