from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

from live.event_bus import EventTags, EventTypes, LIVE_EVENT_DEBUG_PROFILES, ReasonCodes


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "ai" / "generated" / "live_event_registry.md"


def _registry_values(registry: type) -> list[str]:
    return sorted(
        value
        for name, value in vars(registry).items()
        if name.isupper() and isinstance(value, str)
    )


def _section(title: str, values: Iterable[str]) -> str:
    rows = "\n".join(f"- `{value}`" for value in sorted(values))
    return f"## {title}\n\n{rows}\n"


def render_registry() -> str:
    parts = [
        "# Generated Live Event Registry\n\n",
        "<!-- Generated by src/tools/generate_live_event_registry.py; do not edit manually. -->\n\n",
        "The code-owned registries live in `src/live/event_bus.py`. Payload and emission contracts "
        "are documented in `../features/live_events.md`.\n\n",
        _section("Event Types", _registry_values(EventTypes)),
        "\n",
        _section("Event Tags", _registry_values(EventTags)),
        "\n",
        _section("Reason Codes", _registry_values(ReasonCodes)),
        "\n",
        _section("Debug Profiles", LIVE_EVENT_DEBUG_PROFILES),
    ]
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the live event registry documentation")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if committed output is stale")
    args = parser.parse_args()

    rendered = render_registry()
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            print(f"stale generated documentation: {args.output}")
            return 1
        print(f"generated documentation is current: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
